name: Self hosted runner

on:
  workflow_call:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7
        with:
          ref: main

      - uses: voidzero-dev/setup-vp@v1
        with:
          cache: true
          run-install: true

      - run: |
          vp run vp_build
          rsync -avz --delete dist/ /srv/www/raknaDocs/
